# Province base data extraction
Province id, name, development, trade good, center of trade level, culture and religion

In [4]:
import os
import pandas as pd
import re

In [5]:
DESIRED_PROV_DATA = ['owner', 'culture', 'religion', 'hre', 'base_tax', 'base_production', 'trade_goods', 'base_manpower', 'capital', 'is_city', 'center_of_trade']

In [ ]:
EU4_DIR = os.getenv("EU4_INSTALL_LOCATION")
SEPARATOR = os.path.sep
PROV_HISTORY_DIR = EU4_DIR + SEPARATOR + 'history' + SEPARATOR + 'provinces'
assert(os.path.isdir(EU4_DIR))

print(os.listdir(PROV_HISTORY_DIR))

['1-Uppland.txt', '10-Jamtland.txt', '100 - Friesland.txt', '1000 - Cree.txt', '1001 - Sault.txt', '1002 - Abitbi.txt', '1003 - Moose Cree.txt', '1004 - Attawapiskat.txt', '1005 - Swampy Cree.txt', '1006 - Chipewyan.txt', '1007 - Ojibwa.txt', '1008 - Winnipeg.txt', '1009 - Atikaki.txt', '101 - Genoa.txt', '1010 - Manitoba.txt', '1011 - Woods Cree.txt', '1012 - Satsuma.txt', '1013 - Cheongju.txt', '1014 - Bungo.txt', '1015 - Okinawa.txt', '1016 - Ha Tinh.txt', '1017 - Suo.txt', '1018 - Izumo.txt', '1019 - Harima.txt', '102 - Nice.txt', '1020 - Yamashiro.txt', '1021 - Settsu.txt', '1022 - Indrapura.txt', '1023 - Echizen.txt', '1024 - Echigo.txt', '1025 - Dewa.txt', '1026 - Rikuzen.txt', '1027 - Hitachi.txt', '1028 - Musashi.txt', '1029 - Kai.txt', '103 - Piedmont.txt', '1030 - Owari.txt', '1031 - Kamikawa.txt', '1032 - Kurils.txt', '1033 - Sakhalin.txt', '1034 - Kamchatka.txt', '1035 - Penchisky.txt', '1036 - Podzhiversk.txt', '1037 - Nizhe-Kolymsk.txt', '1038 - Anadyrsk.txt', '1039 - Verkhoyansk.txt', '104 - Milan.txt', '1040 - Suntar Khayat.txt', '1041 - Gizhiga.txt', '1042 - Kamnuskoye.txt', '1043 - Okhotsk.txt', '1044 - Tauisk.txt', '1045 - Yakutsk.txt', '1046 - Butalsk.txt', '1047 - Jugjur.txt', '1048 - Udskoye.txt', '1049 - Hailanboo.txt', '105 - Parma.txt', '1050 - Deren.txt', '1051 - Uchurskoye.txt', '1052 - Verkohzehkoye.txt', '1053 - Hinggan.txt', '1054 - Ilimsk.txt', '1055 - Verkne-Angarsky.txt', '1056 - Barguzinsky.txt', '1057 - Udinsky.txt', '1058 - Nerchinsky.txt', '1059 - Bratsk.txt', '106 - Modena.txt', '1060 - Irkutsk.txt', '1061 - Yeniseysk.txt', '1062 - Kachinsk.txt', '1063 - Sayan.txt', '1064 - Tomsk.txt', '1065 - Kuznetsk.txt', '1066 - Altai.txt', '1067 - Narym.txt', '1068 - Pegaya Orda.txt', '1069 - Surgut.txt', '107 - Brescia.txt', '1070 - Koda.txt', '1071 - Tara.txt', '1072 - Obdorsk.txt', '1073 - Berezov.txt', '1074 - Sibir.txt', '1075 - Tyumen.txt', '1076 - Kurgan.txt', '1077 - Solikamsk.txt', '1078 - Middle Urals.txt', '1079 - Viatka.txt', '108 - Verona.txt', '1080 - North Urals.txt', '1081 - Simbirsk.txt', '1082 - Kazan.txt', '1083 - Zavolochye.txt', '1084 - Wadjuk.txt', '1085 - Paredarerme.txt', '1086 - Kaurna.txt', '1087 - Wurundjeri.txt', '1088 - Wergaia.txt', '1089 - Wiradjuri.txt', '109 - Mantua.txt', '1090 - Eora.txt', '1091 - Kamilaroi.txt', '1092 - Bundjalung.txt', '1093 - Barunggam.txt', '1094 - Turrbal.txt', '1095 - Falklands.txt', '1096 - Cape Verde.txt', '1097 - Fernando Po.txt', '1098 - St. Helena.txt', '1099 - Socotra.txt', '11-Vasterbotten.txt', '110 - Trent.txt', '1100 - Mahe.txt', '1101 - Diego Garcia.txt', '1102 - Mauritius.txt', '1103 - Bourbon.txt', '1104 - Eiriksfjord.txt', '1105 - Vestbygden.txt', '1106 - Te Tai Tokerau.txt', '1107 - Taranaki.txt', '1108 - Te Moana a Toi.txt', '1109 - Timaru.txt', '111 - Friuli.txt', '1110 - Rio de Oro.txt', '1111 - Arguin.txt', '1112 - Trarza.txt', '1113 - Cayor.txt', '1114 - Gabu.txt', '1115 - Brakna.txt', '1116 - Wolof.txt', '1117 - Futa Jallon.txt', '1118 - Sierra Leone.txt', '1119 - Grain Coast.txt', '112 - Venezia.txt', '1120 - Bambuk.txt', '1121 - Bure.txt', '1122 - Bagoe.txt', '1123 - Segu.txt', '1124 - Wasuju.txt', '1125 - Kong.txt', '1126 - Ivory Coast.txt', '1127 - Tuat.txt', '1128 - Taodeni.txt', '1129 - Azawadd.txt', '113 - Ferrara.txt', '1130 - Tadmekka.txt', '1131 - Massina.txt', '1132 - Timbuktu.txt', '1133 - Gao.txt', '1134 - Jenne.txt', '1135 - Yatenga.txt', '1136 - Gurma.txt', '1137 - Wagadugi.txt', '1138 - Kumasi.txt', '1139 - Gold Coast.txt', '114 - Romagna.txt', '1140 - Abomey.txt', '1141 - Whydah.txt', '1142 - Dendi.txt', '1143 - Borgu.txt', '1144 - Oyo.txt', '1145 - Nupe.txt', '1146 - Ife.txt', '1147 - Benin.txt', '1148 - Gobir.txt', '1149 - Katsina.txt', '115 - Pisa.txt', '1150 - Zamfara.txt', '1151 - Bonny.txt', '1152 - Idah.txt', '1153 - Pindinga.txt', '1154 - Zazzau.txt', '1155 - Kano.txt', '1156 - Damagaram.txt', '1157 - Borno.txt', '1158 - Kanem.txt', '1159 - Bagirmi.txt', '116 - Firenze.txt', '1160 - Mandara.txt', '1161 - Bauchi.txt', '1162 - Wukari.txt', '1163 - Calabar.txt', '1164 - Cameroon.txt', '1165 - Gabon.txt', '1166 - Loango.txt', '1167 - Luanda.txt', '1168 - Kisarna.txt', '1169 - Mayombe.txt', '117 - Siena.txt', '1170 - Kongo.txt', '1171 - Ndongo.txt', '1172 - Benguela.txt', '1173 - Damaraland.txt', '1174 - Walvis Bay.txt', '1175 - Lesser Namaqualand.txt', '1176 - Roggeveld.txt', '1177 - Cape.txt', '1178 - Great Karoo.txt', '1179 - Little Karoo.txt', '118 - Roma.txt', '1180 - Transkei.txt', '1181 - Natal.txt', '1182 - Delagoa Bay.txt', '1183 - Inhambane.txt', '1184 - Zimbabwe.txt', '1185 - Buha.txt', '1186 - Sofala.txt', '1187 - Sena.txt', '1188 - Masapa.txt', '1189 - Shangwe.txt', '119 - Ancona.txt', '1190 - Zumbo.txt', '1191 - Tete.txt', '1192 - Quelimane.txt', '1193 - Menabe.txt', '1194 - Boina.txt', '1195 - Mozambique.txt', '1196 - Kilwa.txt', '1197 - Mzizima.txt', '1198 - Lindi.txt', '1199 - Bagamoyo.txt', '12-Sjaelland.txt', '120 - Abbruzzi.txt', '1200 - Tanga.txt', '1201 - Zanzibar.txt', '1202 - Mombasa.txt', '1203 - Malindi.txt', '1204 - Lamu.txt', '1205 - Mogadishu.txt', '1206 - Qardho.txt', '1207 - Ogaden.txt', '1208 - Degehabur.txt', '1209 - Berbera.txt', '121 - Napoli.txt', '1210 - Dawaro.txt', '1211 - Harer.txt', '1212 - Zeila.txt', '1213 - Shoa.txt', '1214 - Awsa.txt', '1215 - Tajura.txt', '1216 - Dar Nuba.txt', '1217 - Fazughli.txt', '1218 - Kefa.txt', '1219 - Kordofan.txt', '122 - Apulia.txt', '1220 - Dar Jaal.txt', '1221 - Taqali.txt', '1222 - Gezira.txt', '1223 - Gojjam.txt', '1224 - Gonder.txt', '1225 - Butana.txt', '1226 - Taka.txt', '1227 - Tigre.txt', '1228 - Dongola.txt', '1229 - Berber.txt', '123 - Calabria.txt', '1230 - Massawa.txt', '1231 - Aswan.txt', '1232 - Suakin.txt', '1233 - Kharga.txt', '1234 - Qasr Ibrim.txt', '1235 - Guam.txt', '1236 - Rabaul.txt', '1237 - Hanuabada.txt', '1238 - Solomon Islands.txt', '1239 - Vanuatu.txt', '124 - Messina.txt', '1240 - Hawaii.txt', '1241 - Kiribati.txt', '1242 - Fiji.txt', '1243 - Samoa.txt', '1244 - Tahiti.txt', '1245 - Manokwari.txt', '1246 - Ata Whenua.txt', '1247 - Corsica.txt', '1248 - Maldives.txt', '1249 - Yola.txt', '125 - Palermo.txt', '1250 - Vanern.txt', '1251 - Vattern.txt', '1252 - Gulf of Bothnia.txt', '1253 - Alands Hav.txt', '1254 - Gulf of Finland.txt', '1255 - Western Baltic Sea.txt', '1256 - Gulf of Riga.txt', '1257 - Southern Baltic Sea.txt', '1258 - Oresund.txt', '1259 - Kattegat.txt', '126 - Malta.txt', '1260 - Peipsi Jarv.txt', '1261 - Ladoga.txt', '1262 - Onega.txt', '1263 - White Sea.txt', '1264 - Lofoten Sea.txt', '1265 - Northern Norwegian Sea.txt', '1266 - Southern Norwegian Sea.txt', '1267 - Skagerrack.txt', '1268 - Helgoland Bight.txt', '1269 - Coast of Holland.txt', '127 - Sassari.txt', '1270 - Dogger Bank.txt', '1271 - Straits of Dover.txt', '1272 - The Channel.txt', '1273 - Taveta.txt', '1274 - Coast of Britanny.txt', '1275 - Quiberon Bay.txt', "1276 - Cote D'Argent.txt", '1277 - Bay of Biscay.txt', '1278 - Cantabrian Sea.txt', '1279 - Tyne.txt', '128 - Karnten.txt', '1280 - Firth of Forth.txt', '1281 - The North Sea.txt', '1282 - Moray Firth.txt', '1283 - North Channel.txt', '1284 - Irish Sea.txt', "1285 - St. George's Channel.txt", '1286 - Donegal Bay.txt', '1287 - Dingle Bay.txt', '1288 - Celtic Sea.txt', '1289 - Western Approaches.txt', '129 - Krain.txt', '1290 - Finisterre Bay.txt', '1291 - Lusitanian Sea.txt', '1292 - Gulf of Cadiz.txt', '1293 - Straits of Gibraltar.txt', '1294 - Gulf of Almeira.txt', '1295 - Gulf of Valencia.txt', '1296 - Gulf of Lion.txt', "1297 - Cote D'Azur.txt", '1298 - Ligurian Sea.txt', '1299 - Coast of the Faroes.txt', '13-Slesvig.txt', '130 - Istria.txt', '1300 - Western Mediterranean.txt', '1301 - Barbary Coast.txt', '1302 - Cape Bon.txt', '1303 - Tyrrenean Sea.txt', '1304 - Bay of Naples.txt', '1305 - Gulf of Gabes.txt', '1306 - Sao Tomel.txt', '1307 - Straits of Messina.txt', '1308 - Gulf of Venice.txt', '1309 - Adriatic Sea.txt', '131 - Zagorje.txt', '1310 - Straits of Otranto.txt', '1311 - Gulf of Taranto.txt', '1312 - Ionian Sea.txt', '1313 - Gulf of Sirte.txt', '1314 - Gulf of Tobruk.txt', '1315 - Bay of Alexandrian.txt', '1316 - Palestinian Coast.txt', '1317 - Gulf of Cyprus.txt', '1318 - Spis.txt', '1319 - Aegean Sea.txt', '132 - Steiermark.txt', '1320 - Sea of Marmara.txt', '1321 - Gulf of Varna.txt', '1322 - Gulf of Odessa.txt', '1323 - Sea of Azov.txt', '1324 - Eastern Black Sea.txt', '1325 - Lake Balaton.txt', '1326 - Caspian Sea.txt', '1327 - Aral Sea.txt', '1328 - Gulf of Suez.txt', '1329 - Red Sea.txt', '133 - Linz.txt', '1330 - Straits of Obokk.txt', '1331 - Bal el Mandeb.txt', '1332 - Coast of Mascate.txt', '1333 - Mascate Coast.txt', '1334 - Straits of Hormuz.txt', '1335 - Persian Gulf.txt', '1336 - Gulf of Indus.txt', '1337 - Gulf of Gujarat.txt', '1338 - Laquedive Islands.txt', '1339 - Coast of Malabar.txt', '134 - Wien.txt', '1340 - Comorin Cape.txt', '1341 - Coast of Caramandel.txt', '1342 - Coast of Orissa.txt', '1343 - Ganges Delta.txt', '1344 - Akyab Bay.txt', '1345 - Irrawady Delta.txt', '1346 - Andaman Sea.txt', '1347 - Mergui Archipelago.txt', '1348 - Straits of Malacca.txt', '1349 - Nicobar Isles.txt', '135 - Sopron.txt', '1350 - Coast of Atjeh.txt', '1351 - Coast of Sumatra.txt', '1352 - Christmas Island.txt', '1353 - Coast of Java.txt', '1354 - Coast of Surabaya.txt', '1355 - Straits of Lombok.txt', '1356 - Timor Sea.txt', '1357 - The Moluccas.txt', '1358 - Java Sea.txt', '1359 - Straits of Makassar.txt', '136 - Dalmatia.txt', '1360 - Karimata Strait.txt', '1361 - Straits of Johore.txt', '1362 - Malayan Sea.txt', '1363 - Coast of Sarawk.txt', '1364 - Mekong Delta.txt', '1365 - Gulf of Siam.txt', '1366 - Cam Rah Bay.txt', '1367 - South China Sea.txt', '1368 - Coast of Brunei.txt', '1369 - Coast of Annam.txt', '137 - Ragusa.txt', '1370 - Gulf of Tonkin.txt', '1371 - Guanghou Bay.txt', '1372 - Taiwan Strait.txt', '1373 - Yang Tse Delta.txt', '1374 - Yellow Sea.txt', '1375 - Korea Bay.txt', '1376 - South Korean Sea.txt', '1377 - North Korean Sea.txt', '1378 - Coast of Olga.txt', '1379 - Tatar Straits.txt', '138 - Zeta.txt', '1380 - Amur Delta.txt', '1381 - Baj of Ayan.txt', '1382 - Bay of Komenskoie.txt', '1383 - Coast of Kamchatska.txt', '1384 - Oktothsk Sea.txt', '1385 - Coast Sahkalin.txt', '1386 - Soya Strait.txt', '1387 - Tsugaru Strait.txt', '1388 - Sea of Japan.txt', '1389 - Amakusa Sea.txt', '139 - Hum.txt', '1390 - Setto Inland Sea.txt', '1391 - Tokai Sea.txt', '1392 - Ryukyu Islands.txt', '1393 - Luzon Strait.txt', '1394 - Paracel Islands.txt', '1395 - Manila Bay.txt', '1396 - Coast of Luzon.txt', '1397 - Gulf of Leyte.txt', '1398 - Sulu Sea.txt', '1399 - Sea of Celebes.txt', '14-Fyn.txt', '140 - Bosnia.txt', '1400 - Sea of Ternete.txt', '1401 - Sea of Banda.txt', '1402 - Philipine Sea.txt', '1403 - Palau Islands.txt', '1404 - Biak Bay.txt', '1405 - Vilian Strait.txt', '1406 - Trobrian Islands.txt', '1407 - Torres Strait.txt', '1408 - Arafuam Sea.txt', '1409 - Kolepom Bay.txt', '141 - Serbia.txt', '1410 - Gulf of Carpentaria.txt', '1411 - Great Barrier Reef.txt', '1412 - Capricorn Bay.txt', '1413 - Cape Howe.txt', '1414 - Bass Strait.txt', '1415 - Kangaroo Island.txt', '1416 - Great Australian Bight.txt', '1417 - Cape Leuwiin.txt', '1418 - Shark Bay.txt', '1419 - Northwest Cape.txt', '142 - Corfu.txt', '1420 - King Sound.txt', '1421 - Tasman Sea.txt', '1422 - Southern Tasman Sea.txt', '1423 - Cook Strait.txt', '1424 - Northern Tasman Sea.txt', '1425 - Cape Farwell.txt', '1426 - Coast of New Zealand.txt', '1427 - Cantebury Bight.txt', '1428 - Sea of Antarctica.txt', '1429 - New Caledonian Sea.txt', '143 - Vlore.txt', '1430 - Coral Sea.txt', '1431 - Gilbert Sea.txt', '1432 - Solomon Sea.txt', '1433 - Nauru Island.txt', '1434 - Melanesia Sea.txt', '1435 - Micronesia Sea.txt', '1436 - Yap Islands.txt', '1437 - Mariana Islands.txt', '1438 - Tinian Sea.txt', '1439 - Iwo Jima Sea.txt', '144 - Janina.txt', '1440 - Taihei Ocean.txt', '1441 - The Kuriles.txt', '1442 - Bay of Uka.txt', '1443 - Bay of Oljut.txt', '1444 - Bay of Anadyr.txt', '1445 - Bering Sea.txt', '1446 - Horn of Africa.txt', '1447 - Coast of Pepper.txt', '1448 - Zanzibar Strait.txt', '1449 - Mozambique Channel.txt', '145 - Morea.txt', '1450 - Diego Suarez Bay.txt', '1451 - Western Arabian Sea.txt', '1452 - Eastern Arabian Sea.txt', '1453 - The Seychelles.txt', '1454 - Coast of Tamatave.txt', '1455 - The Mascareignes.txt', '1456 - Gulf of Zambeze.txt', '1457 - Coast of Natal.txt', '1458 - Coast of Transkei.txt', '1459 - Coast of Ciskei.txt', '146 - Athens.txt', '1460 - Cape of Good Hope.txt', '1461 - Coast of Namibia.txt', '1462 - Coast of Angola.txt', '1463 - Gulf of Kongo.txt', '1464 - Coast of Cameroon.txt', '1465 - Gulf of Nigeria.txt', '1466 - Ivory Coast.txt', '1467 - Gold Coast.txt', '1468 - Coast of Gamvia.txt', '1469 - Coast of Guinea.txt', '147 - Salonica.txt', '1470 - Maueretanian Coast.txt', '1471 - Canarian Sea.txt', '1472 - Coast of Morocco.txt', '1473 - Jan Mayen Sea.txt', '1474 - Spitzberg Sea.txt', '1475 - Icelandic Sea.txt', '1476 - Shetland Straits.txt', '1477 - Coast of Iceland.txt', '1478 - Northeastern Atlantic.txt', '1479 - Rockall.txt', '148 - Thessaloniki.txt', '1480 - Denmark Strait.txt', '1481 - Eastern Coast of Greenland.txt', '1482 - Western Coast of Greenland.txt', '1483 - Labrador Strait.txt', '1484 - Baffin Bay.txt', '1485 - Hudson Straits.txt', '1486 - James Bay.txt', '1487 - Western Hudson Bay.txt', '1488 - Eastern Hudson Bay.txt', '1489 - Foxe Bassin.txt', '149 - Edirne.txt', '1490 - Gulf of St. Lawrence.txt', '1491 - Cabot Strait.txt', '1492 - Bay of Fundy.txt', '1493 - Strait of Belle Isle.txt', '1494 - Fortune Bay.txt', '1495 - Notre Dame Bay.txt', '1496 - Labrador Sea.txt', '1497 - Greenland Sea.txt', '1498 - Northern Atlantic.txt', '1499 - Masschusetts Bay.txt', '15-Jylland.txt', '150 - Tarnovo.txt', '1500 - Chesapaeake Bay.txt', '1501 - Cape Hatteras.txt', '1502 - Coast of Carolina.txt', '1503 - Coast of Florida.txt', '1504 - Sea of Sargassos.txt', '1505 - Florida Straits.txt', '1506 - Apalachee Bay.txt', '1507 - Mobile Bay.txt', '1508 - Galveston Bay.txt', '1509 - Tampico Bay.txt', '151 - Constantinople.txt', '1510 - Yucatan Sea.txt', '1511 - Gulf of Mexico.txt', '1512 - Yucatan Channel.txt', '1513 - Belize Bay.txt', '1514 - Moscitos Coast.txt', '1515 - Gulf of Darien.txt', '1516 - Jamica Channel.txt', '1517 - Central Carribean.txt', '1518 - Northwestern Carribean.txt', '1519 - Venezualan Gulf.txt', '152 - Belovar.txt', '1520 - Venezuelan Sea.txt', '1521 - Eastern Carribean.txt', '1522 - Windward Islands.txt', '1523 - Lesser Antilles.txt', '1524 - Turks & Caicos Sea.txt', '1525 - Coast of Cuba.txt', '1526 - Coast of Hispaniola.txt', '1527 - Guyana Coast.txt', '1528 - Bay of Belem.txt', '1529 - Amazonas Gulf.txt', '153 - Pest.txt', '1530 - Coast of Brazil.txt', '1531 - Coast of Recife.txt', '1532 - Coast of Pernambuc.txt', '1533 - Todos Santos Bay.txt', '1534 - Rio De Janeiro.txt', '1535 - Baia Parangua.txt', '1536 - Rio De La Plata.txt', '1537 - Bahia Blanca.txt', '1538 - Coast of Patagonia.txt', '1539 - Magellan Strait.txt', '154 - Hont.txt', '1540 - South Chilean Coast.txt', '1541 - Coast of Chile.txt', '1542 - Atacama Coast.txt', '1543 - Arica Gulf.txt', '1544 - Arequipa Bay.txt', '1545 - Coast of Peru.txt', '1546 - Guayaguil Bay.txt', '1547 - Coast of Ecuador.txt', '1548 - Gulf of Panama.txt', '1549 - Bay of Costa Rica.txt', '155 - Bekes.txt', '1550 - Acapulco Bay.txt', '1551 - Manzazilla Bay.txt', '1552 - Mazatlan Bay.txt', '1553 - Gulf of California.txt', '1554 - Coast of Baja.txt', '1555 - Coast of California.txt', '1556 - Santa Catalina Islands.txt', '1557 - Coast of Oregon.txt', '1558 - Coast of Columbia.txt', '1559 - Hecate Strait.txt', '156 - Temes.txt', '1560 - Gulf of Alaska.txt', '1561 - Coast of Alaska.txt', '1562 - Kuskowim Bay.txt', '1563 - Hatton Bank.txt', '1564 - Eastern Gibbs Fracture.txt', '1565 - Western Gibbs Fracture.txt', '1566 - Iberian Shelf.txt', '1567 - Sea of Azores.txt', '1568 - Corner Seamounts.txt', '1569 - New England Seamounts.txt', '157 - Bihar.txt', '1570 - Sable Island Bank.txt', '1571 - Blake Plataeu.txt', '1572 - West Bermuda Sea.txt', '1573 - East Bermuda Sea.txt', '1574 - Some Funny Seaname.txt', '1575 - Northern Guiana Basin.txt', '1576 - Guiana Basin.txt', '1577 - Southern Guiana Basin.txt', '1578 - Canary Approach.txt', '1579 - Cap Verde Approach.txt', '158 - Maros.txt', '1580 - Central Atlantic 1.txt', '1581 - Central Atlantic 2.txt', '1582 - Central Atlantic 3.txt', '1583 - Central Atlantic 4.txt', '1584 - Romanche Gap.txt', '1585 - East Guinea Basin.txt', '1586 - West Guinea Basin.txt', '1587 - Coast of Falklands.txt', '1588 - New Georgia Islands.txt', '1589 - Western Atlantic 1.txt', '159 - Silistria.txt', '1590 - Western Atlantic 2.txt', '1591 - Western Atlantic 3.txt', '1592 - Western Atlantic 4.txt', '1593 - Western Atlantic 5.txt', '1594 - Western Atlantic 6.txt', '1595 - East of Magellans.txt', '1596 - Central Atlantic 5.txt', '1597 - Central Atlantic 6.txt', '1598 - Central Atlantic 7.txt', '1599 - Central Atlantic 8.txt', '16-Bohuslan.txt', '160 - Oltenia.txt', '1600 - Eastern Atlantic 1.txt', '1601 - Eastern Atlantic 2.txt', '1602 - Eastern Atlantic 3.txt', '1603 - Eastern Atlantic 4.txt', '1604 - Eastern Atlantic 5.txt', '1605 - Eastern Atlantic 6.txt', '1606 - Southern Atlantic 1.txt', '1607 - Southern Atlantic 2.txt', '1608 - Southern Atlantic 3.txt', '1609 - Southern Atlantic 4.txt', '161 - Tirgoviste.txt', '1610 - Cape of Storms.txt', '1611 - Gulf of Bengal.txt', '1612 - Northen Bay of Bengal.txt', '1613 - Southern Bay of Bengal.txt', '1614 - Ceylon Sea.txt', '1615 - Coast of Maldives.txt', '1616 - Indian Ocean 1.txt', '1617 - Indian Ocean 2.txt', '1618 - Indian Ocean 3.txt', '1619 - Indian Ocean 4.txt', '162 - Zemplen.txt', '1620 - Indian Ocean 5.txt', '1621 - Indian Ocean 6.txt', '1622 - Indian Ocean 7.txt', '1623 - Indian Ocean 8.txt', '1624 - Indian Ocean 9.txt', '1625 - Indian Ocean 10.txt', '1626 - Indian Ocean 11.txt', '1627 - Indian Ocean 12.txt', '1628 - Indian Ocean 13.txt', '1629 - Indian Ocean 14.txt', '163 - Crete.txt', '1630 - Indian Ocean 15.txt', '1631 - Indian Ocean 16.txt', '1632 - Indian Ocean 17.txt', '1633 - Indian Ocean 18.txt', '1634 - Indian Ocean 19.txt', '1635 - Indian Ocean 20.txt', '1636 - Indian Ocean 21.txt', '1637 - Indian Ocean 22.txt', '1638 - Indian Ocean 23.txt', '1639 - Indian Ocean 24.txt', '164 - Naxos.txt', '1640 - Indian Ocean 25.txt', '1641 - Indian Ocean 26.txt', '1642 - Indian Ocean 27.txt', '1643 - Indian Ocean 28.txt', '1644 - Indian Ocean 29.txt', '1645 - Indian Ocean 30.txt', '1646 - Indian Ocean 31.txt', '1647 - Indian Ocean 32.txt', '1648 - Lake Tchad.txt', '1649 - Lake Victoria.txt', '165 - Bern.txt', '1650 - Lake Tangayika.txt', '1651 - Lake Malawi.txt', '1652 - Lake Kama.txt', '1653 - Lake Balchasj.txt', '1654 - Lake Bajkal.txt', '1655 - Poyang Lake.txt', '1656 - Lake Titicaca.txt', '1657 - Lake Nicaragua.txt', '1658 - Everglades.txt', '1659 - Lake Ontario.txt', '166 - Schwyz.txt', '1660 - Lake Erie.txt', '1661 - Lake Huron.txt', '1662 - Lake Michigan.txt', '1663 - Lake Superior.txt', '1664 - Lake Nipigon.txt', '1665 - Lake Winnipeg.txt', '1666 - Western Pacific 1.txt', '1667 - Western Pacific 2.txt', '1668 - Western Pacific 3.txt', '1669 - Western Pacific 4.txt', '167 - Caux.txt', '1670 - Western Pacific 5.txt', '1671 - Western Pacific 6.txt', '1672 - Western Pacific 7.txt', '1673 - Western Pacific 8.txt', '1674 - Western Pacific 9.txt', '1675 - Western Pacific 10.txt', '1676 - Western Pacific 11.txt', '1677 - Northern Pacific 1.txt', '1678 - Northern Pacific 2.txt', '1679 - Northern Pacific 3.txt', '168 - Normandie.txt', '1680 - Northern Pacific 4.txt', '1681 - Northern Pacific 5.txt', '1682 - Northern Pacific 6.txt', '1683 - Northern Pacific 7.txt', '1684 - Northern Pacific 8.txt', '1685 - Northern Pacific 9.txt', '1686 - Northern Pacific 10.txt', '1687 - Central Pacific 1.txt', '1688 - Central Pacific 2.txt', '

In [5]:
def clean_and_extract_filename(filename):
    if '-' not in filename:
        reg = re.compile(r'\D\w+')
        name_start = re.search(reg, filename).start()
        filename = filename[:name_start] + '-' + filename[name_start:]
    path_no_spaces = filename.replace(' ', '')
    path_no_ext = path_no_spaces.split('.')[0]
    path_id_name = path_no_ext.split('-')
    province_id = path_id_name[0]
    province_name = path_id_name[1]
    return filename, province_id, province_name

In [6]:
def identify_and_clean_line(line):
    line = line.strip()
    line = line.replace('"', '')
    if '#' in line:
        return None, None
    if len(line) < 1:
        return None, None
    args = line.split(' ')
    if len(args) != 3:
        return None, None
    key = args[0]
    value = args[2]
    return key, value

In [7]:
def read_province_file(path, filename):
    filename, province_id, province_name = clean_and_extract_filename(filename)
    province_dict = {}
    with open(path) as file:
        for line in file:
            key, value = identify_and_clean_line(line)
            if key in DESIRED_PROV_DATA and key not in province_dict.keys():
                province_dict.update({key: value})
    for expected_key in DESIRED_PROV_DATA:
        if expected_key not in province_dict.keys():
            province_dict.update({expected_key: None})
    province_dict.update({'name': province_name, 'id': province_id})
    return province_dict

In [8]:
data = []
for file in os.listdir(PROV_HISTORY_DIR):
    province_dict = read_province_file(PROV_HISTORY_DIR + SEPARATOR + file, file)
    data.append(province_dict)
df = pd.DataFrame(data)

In [9]:
df.index = df.index.astype(int)
df = df.sort_index()
df.head()

,owner,culture,religion,hre,base_tax,base_production,trade_goods,base_manpower,capital,is_city,center_of_trade,name,id
0,SWE,swedish,catholic,no,5,5,grain,3,Stockholm,yes,2,Uppland,1
1,NOR,NaN,catholic,no,1,1,fur,1,Frösön,yes,NaN,Jamtland,10
2,FRI,frisian,catholic,yes,6,6,livestock,2,Leeuwarden,yes,NaN,Friesland,100
3,ENG,cree,totemism,no,1,2,unknown,1,Cree,yes,NaN,Cree,1000
4,FRA,anishinabe,totemism,no,2,2,unknown,1,Sault,yes,NaN,Sault,1001

In [10]:
df.isna().sum()

owner               887
culture             686
religion            868
hre                 651
base_tax            652
base_production     656
trade_goods         761
base_manpower       653
capital             893
is_city             989
center_of_trade    3561
name                  0
id                    0
dtype: int64

In [11]:
df['owner'] = df['owner'].fillna('Unowned')
df['culture'] = df['culture'].fillna('Unowned')
df['religion'] = df['religion'].fillna('Unowned')
df['hre'] = df['hre'].fillna('no')
df['base_tax'] = df['base_tax'].fillna(0)
df['base_production'] = df['base_production'].fillna(0)
df['base_manpower'] = df['base_manpower'].fillna(0)
df['capital'] = df['capital'].fillna(df['name'])
df['is_city'] = df['is_city'].fillna('no')
df['center_of_trade'] = df['center_of_trade'].fillna(0)

## Trade nodes

In [12]:
def process_tradenode_file_line(line, node_data, inland, end_node, location, members, trade_node, in_members_segment):
    line = line.strip()
    if 'in_members_segment' not in locals():
        in_members_segment = False
    if 'trade_node' not in locals():
        trade_node = ''
    if re.match(node_name_regex, line):
        if len(trade_node) > 0:
            node_data.append([trade_node, inland, end_node, len(members), location])
        # Initialise all node values
        inland = False
        end_node = False
        location = None
        members = []
        trade_node = line.strip().rstrip('={') # Remove whitespace before removing ={
        return node_data, inland, end_node, location, members, trade_node, in_members_segment
    if re.match(members_list_regex, line):
        in_members_segment = True
        return node_data, inland, end_node, location, members, trade_node, in_members_segment
    if in_members_segment and re.match(numbers_in_members_list_regex, line):
        for member in line.strip().split(' '):
            members.append(member)
        for member in members:
            df.loc[df['id'] == member, 'trade_node'] = trade_node
        in_members_segment = False
        return node_data, inland, end_node, location, members, trade_node, in_members_segment
    try:
        split_line = line.split('=')
    except:
        assert('=' not in line)
    if split_line:
        if split_line[0].strip() == 'inland' and split_line[1].strip() == 'yes':
            inland = True
            return node_data, inland, end_node, location, members, trade_node, in_members_segment
        if split_line[0].strip() == 'end' and split_line[1].strip() == 'yes':
            end_node = True
            return node_data, inland, end_node, location, members, trade_node, in_members_segment
        if split_line[0].strip() == 'location':
            location = int(split_line[1].strip())
    if in_members_segment and '}' in line and not re.match(numbers_in_members_list_regex, line):
        in_members_segment = False
    return node_data, inland, end_node, location, members, trade_node, in_members_segment

In [13]:
def initialise_tradenode_context():
    inland = False
    end_node = False
    location = None
    in_members_segment = False
    members = []
    node_data = []
    trade_node = ''
    return inland, end_node, location, in_members_segment, members, node_data, trade_node

In [14]:
trade_nodes_path = EU4_DIR + SEPARATOR + 'common' + SEPARATOR + 'tradenodes' + SEPARATOR + '00_tradenodes.txt'
node_name_regex = re.compile(r'\b(?!color\b)(?!outgoing\b)(?!path\b)(?!control\b)(?!members\b)\w+=\{')
members_list_regex = re.compile(r'(members={)')
numbers_in_members_list_regex = re.compile(r'\w+(\d+)\w')
df['trade_node'] = None
inland, end_node, location, in_members_segment, members, node_data, trade_node = initialise_tradenode_context()
with open(trade_nodes_path) as nodefile:
    for line in nodefile:
        node_data, inland, end_node, location, members, trade_node, in_members_segment = process_tradenode_file_line(line, node_data, inland, end_node, location, members, trade_node, in_members_segment)
df_trade_nodes = pd.DataFrame(data=node_data, columns=['name', 'inland', 'end_node', 'member_count', 'location'])

In [15]:
df_trade_nodes

                   name  inland  end_node  member_count  location
0   african_great_lakes    True     False            30      4064
1                 kongo    True     False            32      4097
2               zambezi    True     False            29      1191
3             patagonia   False     False            20      2868
4         amazonas_node   False     False            37      2935
..                  ...     ...       ...           ...       ...
74              sevilla   False     False            53      1293
75            champagne    True     False            33       186
76             valencia   False     False            22      1295
77                genua   False      True            42      1298
78               venice   False      True            26      1308

[79 rows x 5 columns]

In [16]:
df.loc[df["owner"] == 'MAL']

,owner,culture,religion,hre,base_tax,base_production,trade_goods,base_manpower,capital,is_city,center_of_trade,name,id,trade_node
129,MAL,senegambian,Unowned,no,3,3,ivory,2,Kansala,yes,1,Gabu,1114,ivory_coast
132,MAL,fulani,Unowned,no,3,3,ivory,3,Timbo,yes,0,FutaJallon,1117,ivory_coast
136,MAL,soninke,Unowned,no,6,6,gold,2,Bambuk,yes,0,Bambuk,1120,timbuktu
137,MAL,mali,Unowned,no,6,6,gold,2,Kurussa,yes,0,Bure,1121,timbuktu
138,MAL,dyola,Unowned,no,1,1,dyes,1,Tingrela,yes,0,Bagoe,1122,timbuktu
139,MAL,bambara,Unowned,no,5,5,grain,2,Kirina,yes,0,Segu,1123,timbuktu
140,MAL,mali,Unowned,no,4,4,grain,8,Niani,yes,1,Wasuju,1124,timbuktu
1376,MAL,senegambian,Unowned,no,1,1,ivory,1,Sutuco,yes,0,Kantor,2238,ivory_coast
1382,MAL,soninke,sunni,no,1,1,livestock,1,Awdaghust,yes,0,Termes,2243,timbuktu
1384,MAL,soninke,Unowned,no,2,2,wool,1,Dia,yes,0,Wagadu,2245,timbuktu
1387,MAL,mali,Unowned,no,4,4,livestock,1,Walata,yes,0,Do,2248,timbuktu
1388,MAL,mali,Unowned,no,2,2,spices,1,Bamako,yes,0,Sibiridugu,2249,timbuktu
1390,MAL,bozo,Unowned,no,3,3,iron,1,San,yes,0,Bendugu,2250,timbuktu

In [17]:
df.to_csv('./data/provinces_stage1.csv')